dist: trusty
language: ruby

rvm:
  - 2.3.3
  - 2.4.2

services:
  - sqlite3

before_install:
  - mysql - e 'CREATE DATABASE IF NOT EXISTS template_test;'

script:
  - bundle exec rails db:migrate RAILS_ENV=test
  - bundle exec rspec
